#!/usr/bin/env python2

# ***** BEGIN LICENSE BLOCK *****
# 
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
# 
# Copyright (C) 2011-2012 Matthew Turnbull <sparky@bluefang-logic.com>. All Rights Reserved.
# 
# ***** END LICENSE BLOCK *****

import re
import os
import codecs
from datetime import datetime
from xml.sax.saxutils import escape

propRE = re.compile(r"^\s*([a-zA-Z.]+)\s*=\s*(.+?)\s*(#.*)?$", re.U)

targetIds = {
	"Firefox": "{ec8030f7-c20a-464f-9b0e-13a3a9e97384}",
	"SeaMonkey": "{92650c4d-4b8e-4d2a-b7eb-24ecf4f6b63a}"
}

rdfProps = [
	"name",
	"description",
	"id",
	"version",
	"creator",
	"developer",
	"translator",
	"contributor",
	"type",
	"bootstrap",
	"unpack",
	"strictCompatibility",
	"aboutURL",
	"homepageURL",
	"icon64URL",
	"iconURL",
	"optionsType",
	"optionsURL",
	"updateKey",
	"updateURL",
	"multiprocessCompatible"
]

rdfPropsMulti = [
	"developer",
	"translator",
	"contributor"
]

def parsePropFile(filename):
	props = {}

	with codecs.open(filename, mode="r", encoding="utf-8") as f:
		for line in f:
			result = propRE.search(line)
			if result:
				props[result.group(1)] = result.group(2)

	return props

def parseL10N(l10nDir):
	langs = {}

	for l10n in os.listdir(l10nDir):
		l10nMeta = os.path.join(l10nDir, l10n, "meta.properties")
		if os.path.isfile(l10nMeta):
			langs[l10n] = parsePropFile(l10nMeta)
		else:
			print "WARNING: could not find %s" % l10nMeta

	return langs

def getConfig():
	props = parsePropFile("install.manifest")
	langs = parseL10N("chrome/locale/")

	defaultLocale = langs[props["defaultLocale"]]
	del langs[props["defaultLocale"]]
	del props["defaultLocale"]

	info = {}
	targets = {}

	for prop in props:
			val = props[prop]
			if prop in targetIds:
				val = val.split('|')
				target = {
					"id": targetIds[prop],
					"min": val[0],
					"max": val[1]
				}
				targets[prop] = target
				continue;

			if prop in rdfPropsMulti:
				val = val.split('|')

			if prop in rdfProps:
				info[prop] = val

	info["name"] = defaultLocale["name"]
	info["description"] = defaultLocale["description"]

	return (info, targets, langs)

def buildManafest():
	(info, targets, locales) = getConfig()
	f = codecs.open("install.rdf", mode="w", encoding="utf-8")

	#
	# Print the header
	#
	f.write(u"""<?xml version="1.0" encoding="UTF-8"?>

<!-- ***** BEGIN LICENSE BLOCK *****
   - 
   - This Source Code Form is subject to the terms of the Mozilla Public
   - License, v. 2.0. If a copy of the MPL was not distributed with this
   - file, You can obtain one at http://mozilla.org/MPL/2.0/.
   - 
   - Copyright (C) %s Matthew Turnbull <sparky@bluefang-logic.com>. All Rights Reserved.
   - 
   - ***** END LICENSE BLOCK ***** -->

<RDF xmlns="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:em="http://www.mozilla.org/2004/em-rdf#">
	<Description about="urn:mozilla:install-manifest">\n""" % (datetime.now().year))

	#
	# Print extension info blocks
	#

	f.write(u"""
		<!-- Info -->\n""")

	keys = info.keys()
	keys.sort()
	for prop in rdfProps:
		if prop in info:
			if prop in rdfPropsMulti:
				for val in info[prop]:
					f.write(u"""
		<em:%s>%s</em:%s>""" % (prop, escape(val), prop))
			else:
				f.write(u"""
		<em:%s>%s</em:%s>""" % (prop, escape(info[prop]), prop))
	f.write(u"""\n""")

	#
	# Print the locale blocks
	#

	f.write(u"""
		<!-- Localizations -->\n""")

	keys = locales.keys()
	keys.sort()
	for locale in keys:
		l10n = locales[locale]
		translators = ""
		for t in l10n["translator"].split(","):
			translators += u"""<em:translator>%s [%s]</em:translator>""" % (escape(t.strip()), locale)
		f.write(u"""
		<em:localized><!-- %s -->
			<Description>
				<em:locale>%s</em:locale>
				<em:name>%s</em:name>
				<em:description>%s</em:description>
				<em:creator>%s</em:creator>
				<em:homepageURL>%s</em:homepageURL>
				%s
			</Description>
		</em:localized>\n""" % (locale, locale, escape(l10n["name"]), escape(l10n["description"]), escape(info["creator"]), escape(info["homepageURL"]), translators))

	#
	# Print target blocks
	#

	f.write(u"""
		<!-- Targets -->\n""")

	keys = targets.keys()
	keys.sort()
	for t in keys:
		target = targets[t]
		f.write(u"""
		<em:targetApplication><!-- %s -->
			<Description>
				<em:id>%s</em:id>
				<em:minVersion>%s</em:minVersion>
				<em:maxVersion>%s</em:maxVersion>
			</Description>
		</em:targetApplication>\n""" % (t, target["id"], target["min"], target["max"]))

	#
	# Print the footer
	#

	f.write("""
	</Description>
</RDF>\n""")

if __name__ == "__main__":
	buildManafest()

